use axum::{
    Json, Router,
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::{get, post},
};
use serde::{Deserialize, Serialize};
use sqlx::mysql::MySqlPoolOptions;
use sqlx::{FromRow, MySqlPool};

#[derive(Deserialize)]
struct CreateUser {
    username: String,
    email: String,
}

#[derive(Serialize)] // <--- Add the trait
struct UserResponse {
    id: u64,
    username: String,
}

#[derive(Serialize, FromRow)]
struct User {
    id: i32, // MySQL INT fits into Rust i32
    username: String,
    email: String,
}

#[tokio::main]
async fn main() {
    let pool = MySqlPoolOptions::new()
        .max_connections(5)
        .connect("mysql://rust:rust@localhost:3306/rust_api")
        .await
        .expect("Failed to connect to MySQL");

    match pool.acquire().await {
        Ok(_) => println!("Successfully connected to the database."),
        Err(e) => {
            eprintln!("Failed to connect to the database: {}", e);
            return;
        }
    }

    let query_result = sqlx::query(
        "CREATE TABLE IF NOT EXISTS users(
        id INT AUTO_INCREMENT PRIMARY KEY,
            username VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL
        )",
    )
    .execute(&pool)
    .await
    .expect("Failed to create users table");

    match query_result.rows_affected() {
        0 => println!("Table 'users' already exists."),
        _ => println!("Table 'users' created successfully."),
    }

    let app = Router::new()
        .route("/", get(|| async { "Hello, World!" }))
        .route("/users", post(create_user).get(get_users))
        .with_state(pool);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    println!("Listening on port 3000...");
    axum::serve(listener, app).await.unwrap();
}

// We return Result<SuccessType, ErrorType>
async fn create_user(
    State(pool): State<MySqlPool>,
    Json(payload): Json<CreateUser>,
) -> Result<impl IntoResponse, (StatusCode, String)> {
    // 1. Execute the SQL Insert
    let result = sqlx::query("INSERT INTO users (username, email) VALUES (?, ?)")
        .bind(&payload.username)
        .bind(&payload.email)
        .execute(&pool)
        .await;

    // 2. Handle the Result
    match result {
        Ok(res) => {
            // MySQL allows us to retrieve the ID generated by AUTO_INCREMENT
            let id = res.last_insert_id();

            let response = UserResponse {
                id,
                username: payload.username,
            };

            // Return 201 Created with the JSON body
            Ok((StatusCode::CREATED, Json(response)))
        }
        Err(e) => {
            // Log the error and return 500 Internal Server Error
            // In a real app, do not expose the raw database error to the client
            Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))
        }
    }
}

async fn get_users(State(pool): State<MySqlPool>) -> Result<Json<Vec<User>>, (StatusCode, String)> {
    // fetch_all returns a Vec<User>
    let users = sqlx::query_as::<_, User>("SELECT id, username, email FROM users")
        .fetch_all(&pool)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    Ok(Json(users))
}
